FROM ubuntu:20.04

RUN apt-get update && apt-get install -y nano curl git wget

WORKDIR /home/dastorin

COPY ./script.sh /home/dastorin/script.sh

RUN echo "Hi!!!!"


#my_ubuntu:3 223.4MB

#my_ubuntu:4 374.1MB

#my_ubuntu:5 374.1MB
